---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: app-web-server
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: app-web-server-3a56646b86
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: app-web-server
    name: app-web-server-svc
spec:
    ports:
        - name: metrics
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: app-web-server-3a56646b86
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: app-web-server
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: app-web-server-3a56646b86
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: app-web-server
    name: app-web-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: app-web-server-3a56646b86
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: app-web-server
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: app-web-server-3a56646b86
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: app-web-server
        spec:
            containers:
                - env:
                    - name: FLASK_ENV
                      value: development
                  image: ghcr.io/platform-nexus-rn/app-web-server
                  name: app
                  resources: {}
status: {}
