---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: app-web-api
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: app-web-api-29c2149830
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: app-web-api
    name: app-web-api-svc
spec:
    ports:
        - name: metrics
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: app-web-api-29c2149830
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: app-web-api
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: app-web-api-29c2149830
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: app-web-api
    name: app-web-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: app-web-api-29c2149830
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: app-web-api
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: app-web-api-29c2149830
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: app-web-api
        spec:
            containers:
                - env:
                    - name: FLASK_ENV
                      value: development
                  image: ghcr.io/platform-nexus-rn/app-web-api
                  name: app
                  resources: {}
status: {}
