apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-web-api
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-web-api
  namespaceSelector:
    matchNames:
      - app-web-api
  endpoints:
    - port: metrics
      interval: 5s
