apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-secret-service-5
  namespace: kube-prometheus-stack
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-secret-service-5
  namespaceSelector:
    matchNames:
      - k8s-secret-service-5
  endpoints:
    - port: metrics
      interval: 5s
