---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: python-prometheus-service
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: python-prometheus-service-488518b72a
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: python-prometheus-service
    name: python-prometheus-service-svc
spec:
    ports:
        - name: metrics
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: python-prometheus-service-488518b72a
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: python-prometheus-service
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: python-prometheus-service-488518b72a
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: python-prometheus-service
    name: python-prometheus-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: python-prometheus-service-488518b72a
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: python-prometheus-service
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: python-prometheus-service-488518b72a
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: python-prometheus-service
        spec:
            containers:
                - env:
                    - name: FLASK_ENV
                      value: development
                  image: ghcr.io/platform-nexus-rn/python-prometheus-service
                  name: app
                  resources: {}
status: {}
