{
 "title": "app-web-api HTTP Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "app-web-api - HTTP Requests per Service (Bar Chart)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service) (flask_http_request_total)"
    }
   ]
  },
  {
   "title": "app-web-api - HTTP Requests Rate over Time (Time Series)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])"
    }
   ]
  },
  {
   "title": "app-web-api - Total HTTP Requests (Stat Panel)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(flask_http_request_total)" }
   ]
  }
 ]
}