---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: test123
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: test123-2cb4aa2b10
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: test123
    name: test123-svc
spec:
    ports:
        - name: metrics
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: test123-2cb4aa2b10
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: test123
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: test123-2cb4aa2b10
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: test123
    name: test123
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: test123-2cb4aa2b10
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: test123
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: test123-2cb4aa2b10
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: test123
        spec:
            containers:
                - env:
                    - name: FLASK_ENV
                      value: development
                  image: ghcr.io/platform-nexus-rn/test123
                  name: app
                  resources: {}
status: {}
