apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test123
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test123
  namespaceSelector:
    matchNames:
      - test123
  endpoints:
    - port: metrics
      interval: 5s
