---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: testbkstg12
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: testbkstg12-77467988a9
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: testbkstg12
    name: testbkstg12-svc
spec:
    ports:
        - name: metrics
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: testbkstg12-77467988a9
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: testbkstg12
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: testbkstg12-77467988a9
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: testbkstg12
    name: testbkstg12
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: testbkstg12-77467988a9
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: testbkstg12
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: testbkstg12-77467988a9
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: testbkstg12
        spec:
            containers:
                - env:
                    - name: FLASK_ENV
                      value: development
                  image: ghcr.io/platform-nexus-rn/testbkstg12
                  name: app
                  resources: {}
status: {}
