---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: k8s-secret-service-4
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: k8s-secret-service-4-d61d6260c3
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: k8s-secret-service-4
    name: k8s-secret-service-4-svc
spec:
    ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: metrics
          port: 9100
          protocol: TCP
          targetPort: 9100
    selector:
        app.kubernetes.io/instance: k8s-secret-service-4-d61d6260c3
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: k8s-secret-service-4
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: k8s-secret-service-4-d61d6260c3
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: k8s-secret-service-4
    name: k8s-secret-service-4
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: k8s-secret-service-4-d61d6260c3
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: k8s-secret-service-4
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: k8s-secret-service-4-d61d6260c3
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: k8s-secret-service-4
        spec:
            containers:
                - env:
                    - name: FLASK_ENV
                      value: development
                  image: ghcr.io/platform-nexus-rn/k8s-secret-service-4
                  name: app
                  resources: {}
status: {}
