apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-secret-service-4
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-secret-service-4
  namespaceSelector:
    matchNames:
      - k8s-secret-service-4
  endpoints:
    - port: metrics
      interval: 5s
