apiVersion: score.dev/v1b1
metadata:
  name: python-prometheus-service
service:
  ports:
    metrics:
      port: 8080
      targetPort: 8080
      protocol: TCP
containers:
  app:
    image: ghcr.io/platform-nexus-rn/python-prometheus-service
    variables:
      FLASK_ENV: development
