---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: ruturaj-test-1
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: ruturaj-test-1-a260271481
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: ruturaj-test-1
    name: ruturaj-test-1-svc
spec:
    ports:
        - name: metrics
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: ruturaj-test-1-a260271481
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: ruturaj-test-1
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: ruturaj-test-1-a260271481
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: ruturaj-test-1
    name: ruturaj-test-1
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: ruturaj-test-1-a260271481
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: ruturaj-test-1
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: ruturaj-test-1-a260271481
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: ruturaj-test-1
        spec:
            containers:
                - env:
                    - name: FLASK_ENV
                      value: development
                  image: ghcr.io/platform-nexus-rn/ruturaj-test-1
                  name: app
                  resources: {}
status: {}
