apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: testbkstg9
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: testbkstg9
  namespaceSelector:
    matchNames:
      - testbkstg9
  endpoints:
    - port: metrics
      interval: 5s
