apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ninad-backstage-test
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ninad-backstage-test
  namespaceSelector:
    matchNames:
      - ninad-backstage-test
  endpoints:
    - port: metrics
      interval: 5s
