apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-prom-monitoring-1
  description: A test service to monitor using Prometheus and Backstage
  tags:
    - python
    - prometheus
    - score
  annotations:
    backstage.io/kubernetes-id: test-prom-monitoring-1
    backstage.io/kubernetes-namespace: test-prom-monitoring-1
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
