---
apiVersion: v1
kind: Service
metadata:
    annotations:
        k8s.score.dev/workload-name: argocd-test-service-5
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: argocd-test-service-5-93b8cfb4cb
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: argocd-test-service-5
    name: argocd-test-service-5-svc
spec:
    ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app.kubernetes.io/instance: argocd-test-service-5-93b8cfb4cb
status:
    loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        k8s.score.dev/workload-name: argocd-test-service-5
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: argocd-test-service-5-93b8cfb4cb
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: argocd-test-service-5
    name: argocd-test-service-5
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: argocd-test-service-5-93b8cfb4cb
    strategy: {}
    template:
        metadata:
            annotations:
                k8s.score.dev/workload-name: argocd-test-service-5
            creationTimestamp: null
            labels:
                app.kubernetes.io/instance: argocd-test-service-5-93b8cfb4cb
                app.kubernetes.io/managed-by: score-k8s
                app.kubernetes.io/name: argocd-test-service-5
        spec:
            containers:
                - env:
                    - name: FLASK_ENV
                      value: development
                  image: ghcr.io/platform-nexus-rn/argocd-test-service-5
                  name: app
                  resources: {}
status: {}
