name: Update Manifests
on:
  repository_dispatch:
    types: [update-manifests]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install score CLI
        run: |
          curl -sSL https://score.dev/install.sh | bash

      - name: Generate K8s Manifests
        run: |
          SERVICE_NAME=${{ github.event.client_payload.service }}
          IMAGE=${{ github.event.client_payload.image }}

          cd apps/$SERVICE_NAME/base
          score-k8s generate score.yaml --image=$IMAGE --output ../../overlays/dev/deployment.yaml

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update manifests for $SERVICE_NAME"
          git push