name: Update Manifests

on:
  repository_dispatch:
    types: [update-manifests]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo with Write Access
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up score-k8s CLI
        uses: score-spec/setup-score@v2
        with:
          file: score-k8s
          version: 0.1.5  # or latest
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Initialize score-k8s
        run: |
          cd apps/${{ github.event.client_payload.service }}/base
          pwd
          score-k8s init
          ls -la
          echo "score-k8s initialized in $(pwd)"

      - name: Ensure output directory exists
        run: |
          SERVICE_NAME=${{ github.event.client_payload.service }}
          cd apps/$SERVICE_NAME/base
          mkdir -p ../../overlays/dev

      - run: ls -la ../../overlays/dev
        working-directory: apps/${{ github.event.client_payload.service }}/base

      - name: Generate K8s Manifests
        run: |
          SERVICE_NAME=${{ github.event.client_payload.service }}
          IMAGE=${{ github.event.client_payload.image }}

          echo "🚀 Generating manifests for $SERVICE_NAME with image: $IMAGE"

          cd apps/$SERVICE_NAME/base
          pwd
          ls -la
          echo "Using score-k8s to generate manifests for $SERVICE_NAME"
          echo "Image: $IMAGE"
          echo "Service Name: $SERVICE_NAME"
          echo "Current Directory: $(pwd)"
          score-k8s generate score.yaml --image=$IMAGE --output ../../overlays/dev/deployment.yaml
          echo "After  generation:"
          ls -la ../../overlays/dev

      - name: Copy manifest to repo location
        run: |
          SERVICE_NAME=${{ github.event.client_payload.service }}
          cp apps/$SERVICE_NAME/base/../../overlays/dev/deployment.yaml apps/$SERVICE_NAME/overlays/dev/deployment.yaml

      - name: Debug generated manifest
        run: |
          SERVICE_NAME=${{ github.event.client_payload.service }}
          echo "Generated Manifest Content:"
          cat apps/$SERVICE_NAME/overlays/dev/deployment.yaml


      - name: Clean up score-k8s state
        run: |
          SERVICE_NAME=${{ github.event.client_payload.service }}
          rm -rf apps/$SERVICE_NAME/base/.score-k8s/

      - name: Tree Debug
        run: |
          echo "🗂️ Tree of apps/$SERVICE_NAME:"
          tree apps/$SERVICE_NAME


      - name: Commit and Push
        run: |
          SERVICE_NAME=${{ github.event.client_payload.service }}

          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add apps/$SERVICE_NAME/overlays/dev

          git commit -m "Update deployment for $SERVICE_NAME" || echo "Nothing to commit"

          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/platform-nexus-rn/platform-nexus-deployments.git

          git push

