name: Update Manifests

on:
  repository_dispatch:
    types: [update-manifests]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v3

      - name: Extract payload info
        run: |
          echo "Service: ${{ github.event.client_payload.service }}"
          echo "Image: ${{ github.event.client_payload.image }}"
          SERVICE_NAME="${{ github.event.client_payload.service }}"
          IMAGE="${{ github.event.client_payload.image }}"

          # Optional: Clone the right app template or update manifests here
          # Example: create/update deployment.yaml in apps/$SERVICE_NAME/

          mkdir -p "apps/$SERVICE_NAME"
          cat <<EOF > apps/$SERVICE_NAME/deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: $SERVICE_NAME
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: $SERVICE_NAME
            template:
              metadata:
                labels:
                  app: $SERVICE_NAME
              spec:
                containers:
                  - name: $SERVICE_NAME
                    image: $IMAGE
                    ports:
                      - containerPort: 8080
          EOF

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add apps/${{ github.event.client_payload.service }}/deployment.yaml
          git commit -m "🚀 Add/update deployment for ${{ github.event.client_payload.service }}"
          git push
