apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-repo-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/platform-nexus-rn/platform-nexus-deployments.git
    targetRevision: main
    path: apps/create-repo-1/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: create-repo-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
