apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flipkart-python-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/platform-nexus-rn/platform-nexus-deployments.git
    targetRevision: main
    path: apps/flipkart-python-service/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: flipkart-python-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

