apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-secret-service-5
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/platform-nexus-rn/platform-nexus-deployments.git
    targetRevision: main
    path: apps/k8s-secret-service-5/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-secret-service-5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

