apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kubevirt
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/platform-nexus-rn/kubevirt-deploy'
    targetRevision: HEAD
    path: .
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
