project: default
source:
  repoURL: https://prometheus-community.github.io/helm-charts
  targetRevision: 72.6.2
  chart: kube-prometheus-stack
destination:
  server: https://kubernetes.default.svc
  namespace: kube-prometheus-stack
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
