apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-test-python-service-6
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/platform-nexus-rn/platform-nexus-deployments.git
    targetRevision: main
    path: apps/my-test-python-service-6/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: my-test-python-service-6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

