apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testbkstg1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/platform-nexus-rn/platform-nexus-deployments.git
    targetRevision: main
    path: apps/testbkstg1/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: testbkstg1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

